config/routes.rb
Rails.application.routes.draw do
  resources :resturants
  resources :resturaunts
  get 'pages/about'

  get 'pages/contact'
root 'resturants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resturant.rb
class Resturant < ApplicationRecord
end

app/models/resturaunt.rb
class Resturaunt < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController
  before_action :set_resturant, only: [:show, :edit, :update, :destroy]

  # GET /resturants
  # GET /resturants.json
  def index
    @resturants = Resturant.all
  end

  # GET /resturants/1
  # GET /resturants/1.json
  def show
  end

  # GET /resturants/new
  def new
    @resturant = Resturant.new
  end

  # GET /resturants/1/edit
  def edit
  end

  # POST /resturants
  # POST /resturants.json
  def create
    @resturant = Resturant.new(resturant_params)

    respond_to do |format|
      if @resturant.save
        format.html { redirect_to @resturant, notice: 'Resturant was successfully created.' }
        format.json { render :show, status: :created, location: @resturant }
      else
        format.html { render :new }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resturants/1
  # PATCH/PUT /resturants/1.json
  def update
    respond_to do |format|
      if @resturant.update(resturant_params)
        format.html { redirect_to @resturant, notice: 'Resturant was successfully updated.' }
        format.json { render :show, status: :ok, location: @resturant }
      else
        format.html { render :edit }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resturants/1
  # DELETE /resturants/1.json
  def destroy
    @resturant.destroy
    respond_to do |format|
      format.html { redirect_to resturants_url, notice: 'Resturant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resturant
      @resturant = Resturant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resturant_params
      params.require(:resturant).permit(:name, :address, :phone, :website)
    end
end

app/controllers/resturaunts_controller.rb
class ResturauntsController < ApplicationController
  before_action :set_resturaunt, only: [:show, :edit, :update, :destroy]

  # GET /resturaunts
  # GET /resturaunts.json
  def index
    @resturaunts = Resturaunt.all
  end

  # GET /resturaunts/1
  # GET /resturaunts/1.json
  def show
  end

  # GET /resturaunts/new
  def new
    @resturaunt = Resturaunt.new
  end

  # GET /resturaunts/1/edit
  def edit
  end

  # POST /resturaunts
  # POST /resturaunts.json
  def create
    @resturaunt = Resturaunt.new(resturaunt_params)

    respond_to do |format|
      if @resturaunt.save
        format.html { redirect_to @resturaunt, notice: 'Resturaunt was successfully created.' }
        format.json { render :show, status: :created, location: @resturaunt }
      else
        format.html { render :new }
        format.json { render json: @resturaunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resturaunts/1
  # PATCH/PUT /resturaunts/1.json
  def update
    respond_to do |format|
      if @resturaunt.update(resturaunt_params)
        format.html { redirect_to @resturaunt, notice: 'Resturaunt was successfully updated.' }
        format.json { render :show, status: :ok, location: @resturaunt }
      else
        format.html { render :edit }
        format.json { render json: @resturaunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resturaunts/1
  # DELETE /resturaunts/1.json
  def destroy
    @resturaunt.destroy
    respond_to do |format|
      format.html { redirect_to resturaunts_url, notice: 'Resturaunt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resturaunt
      @resturaunt = Resturaunt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resturaunt_params
      params.require(:resturaunt).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/helpers/resturaunts_helper.rb
module ResturauntsHelper
end

app/views/layouts/_Navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">yelpdemo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About <span class="sr-only">(current)</span></a></li>
        <li><a href="/pages/contact">Contact</a></li>
        
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_bootstrap.html.erb
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

app/views/layouts/_footer.html.erb
  Copyright Reginald Haines

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelpdemo</title>
    <%= csrf_meta_tags %>
      <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
<%= render "layouts/bootstrap" %>
  </head>

  <body>
  
<%= render "layouts/Navbar" %>
<div class= "container-fluid" >
    <%= yield %>
 <%= render "layouts/footer" %>
 </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About me</h1>
<h2> This is a sample application for <a href="http://www.baserails.com">baserails</a> a platform that teaches people to build awsome custome websites with the Ruby on Rails application</h2>
<p>I am a student learning Ruby on Rails Start learning today Testing Sign up and start learning today</p>

app/views/pages/contact.html.erb
<h1>We would love to hear from you</h1>
<p>Contact us a reggie.com</p>

app/views/resturants/_form.html.erb
<%= form_for(resturant) do |f| %>
  <% if resturant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resturant.errors.count, "error") %> prohibited this resturant from being saved:</h2>

      <ul>
      <% resturant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address ,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone ,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website ,class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/resturants/edit.html.erb
<h1>Editing Resturant</h1>

<%= render 'form', resturant: @resturant %>

<%= link_to 'Show', @resturant, class: "btn btn-link" %> |
<%= link_to 'Back', resturants_path, class: "btn btn-link" %>

app/views/resturants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resturants</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resturants.each do |resturant| %>
      <tr>
        <td><%= resturant.name %></td>
        <td><%= resturant.address %></td>
        <td><%= resturant.phone %></td>
        <td><%= resturant.website %></td>
        <td><%= link_to 'Show', resturant,class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_resturant_path(resturant),class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', resturant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resturant', new_resturant_path, class: "btn btn-link" %>

app/views/resturants/new.html.erb
<h1>New Resturant</h1>

<%= render 'form', resturant: @resturant, class: "btn btn-link" %>

<%= link_to 'Back', resturants_path, class: "btn btn-link" %>

app/views/resturants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resturant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @resturant.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resturant.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @resturant.website %>
</p>

<%= link_to 'Edit', edit_resturant_path(@resturant),class: "btn btn-link" %> |
<%= link_to 'Back', resturants_path, class: "btn btn-link" %>

app/views/resturaunts/_form.html.erb
<%= form_for(resturaunt) do |f| %>
  <% if resturaunt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resturaunt.errors.count, "error") %> prohibited this resturaunt from being saved:</h2>

      <ul>
      <% resturaunt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resturaunts/edit.html.erb
<h1>Editing Resturaunt</h1>

<%= render 'form', resturaunt: @resturaunt %>

<%= link_to 'Show', @resturaunt %> |
<%= link_to 'Back', resturaunts_path %>

app/views/resturaunts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resturaunts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resturaunts.each do |resturaunt| %>
      <tr>
        <td><%= resturaunt.name %></td>
        <td><%= resturaunt.address %></td>
        <td><%= link_to 'Show', resturaunt %></td>
        <td><%= link_to 'Edit', edit_resturaunt_path(resturaunt) %></td>
        <td><%= link_to 'Destroy', resturaunt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resturaunt', new_resturaunt_path %>

app/views/resturaunts/new.html.erb
<h1>New Resturaunt</h1>

<%= render 'form', resturaunt: @resturaunt %>

<%= link_to 'Back', resturaunts_path %>

app/views/resturaunts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resturaunt.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @resturaunt.address %>
</p>

<%= link_to 'Edit', edit_resturaunt_path(@resturaunt) %> |
<%= link_to 'Back', resturaunts_path %>